// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using back_end;

namespace back_end.Migrations
{
    [DbContext(typeof(AplicationDbContext))]
    [Migration("20210924020056_Iniciar")]
    partial class Iniciar
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("back_end.Entidades.Lectura", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("SuscriptorId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SuscriptorId");

                    b.ToTable("Lectura");
                });

            modelBuilder.Entity("back_end.Entidades.Suscriptor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Alcantarillado")
                        .HasColumnType("bit");

                    b.Property<bool>("Aseo")
                        .HasColumnType("bit");

                    b.Property<int>("Atraso")
                        .HasColumnType("int");

                    b.Property<bool>("Bloqueo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Inquilinato")
                        .HasColumnType("bit");

                    b.Property<string>("Manzana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Multiusuario")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Residencial")
                        .HasColumnType("bit");

                    b.Property<string>("Seccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Sistema")
                        .HasColumnType("bigint");

                    b.Property<bool>("Urbano")
                        .HasColumnType("bit");

                    b.Property<long?>("UsoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UsoId");

                    b.ToTable("Suscriptor");
                });

            modelBuilder.Entity("back_end.Entidades.Uso", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("Codigo")
                        .HasColumnType("bigint");

                    b.Property<decimal>("CostoRAseo")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("CostoRAseoCasa")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("CostoRCFijo")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("CostoRConsumo")
                        .HasColumnType("decimal(10,3)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estrato")
                        .HasColumnType("int");

                    b.Property<decimal>("IncrementoAlcantarillado")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("IncrementoAseo")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("IncrementoConsumo")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("IncrementoFijo")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("InteresMora")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("OtroSubsidio")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("OtroValor")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("PorcentajeAlcantarillado")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("PorcentajeFinanciacion")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("Rango1")
                        .HasColumnType("decimal(10,3)");

                    b.Property<int>("Rango2")
                        .HasColumnType("int");

                    b.Property<int>("Rango3")
                        .HasColumnType("int");

                    b.Property<decimal>("SubsidioAlcantarillado")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("SubsidioAseo")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("SubsidioConsumo")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("SubsidioFijo")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("Valor1")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("Valor2")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("Valor3")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("ValorAseo")
                        .HasColumnType("decimal(10,3)");

                    b.Property<decimal>("ValorFijo")
                        .HasColumnType("decimal(10,3)");

                    b.HasKey("Id");

                    b.ToTable("Uso");
                });

            modelBuilder.Entity("back_end.Entidades.Lectura", b =>
                {
                    b.HasOne("back_end.Entidades.Suscriptor", "Suscriptor")
                        .WithMany()
                        .HasForeignKey("SuscriptorId");

                    b.Navigation("Suscriptor");
                });

            modelBuilder.Entity("back_end.Entidades.Suscriptor", b =>
                {
                    b.HasOne("back_end.Entidades.Uso", "Uso")
                        .WithMany()
                        .HasForeignKey("UsoId");

                    b.Navigation("Uso");
                });
#pragma warning restore 612, 618
        }
    }
}
